# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53188ba25138e46152d9d0aad74c60988c9ce6eed7d6e5f1e1957a32d62a1fff77ba603a7b46b083e6d2eb532d18a2041533d0a28b09386e36fcab395751841c

test:
  secret_key_base: 72f69cad5f4a75abc373bdd332c451361dbbe4448c0e65029562164a8db1933b48375b1c80e90f6c2abfb08e53b70f4417f1631cf9229bd7d7f8e1c02e0ce4d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
